const topThinkers = {
  Existencialismo: {
    thinkers: [
      {
        name: "Jean-Paul Sartre",
        image: "/persons/sartre.jpg",
        bio: "Filósofo francês, escreveu sobre liberdade, responsabilidade e autenticidade diante do absurdo da vida.",
        quote: "Se você está sozinho quando está sozinho, você está em má companhia.",
        intro: "Obra de introdução ao autor: 'O Existencialismo é um Humanismo'",
        introBuy: "https://www.planetadelivros.com.br/o-existencialismo-e-um-humanismo/208734",
        main: "Obra mais influencial: 'A Náusea'",
        mainBuy: "https://www.planetadelivros.com.br/a-nausea/208735",
      },
      {
        name: "Albert Camus",
        image: "/persons/camus.jpg",
        bio: "Filósofo e escritor francês, explorou o absurdo e a busca por sentido apesar da falta de significado intrínseco.",
        quote: "Não ser amado é falta de sorte, mas não amar é a própria infelicidade.",
        intro: "Obra de introdução ao autor: 'O Mito de Sísifo'",
        introBuy: "https://www.planetadelivros.com.br/o-mito-de-sisifo/208732",
        main: "Obra mais influencial: 'O Estrangeiro'",
        mainBuy: "https://www.planetadelivros.com.br/o-estrangeiro/208733",
      },
      {
        name: "Søren Kierkegaard",
        image: "/persons/kierkegaard.jpg",
        bio: "Filósofo dinamarquês, considerado o pai do existencialismo, focou na subjetividade e na fé individual.",
        quote: "A vida só pode ser compreendida olhando-se para trás; mas só pode ser vivida olhando-se para frente.",
        intro: "Obra de introdução ao autor: 'O Desespero Humano'",
        introBuy: "https://www.planetadelivros.com.br/o-desespero-humano/208744",
        main: "Obra mais influencial: 'Temor e Tremor'",
        mainBuy: "https://www.planetadelivros.com.br/temor-e-tremor/208745",
      },
    ],
  },
  Niilismo: {
    thinkers: [
      {
        name: "Friedrich Nietzsche",
        image: "/persons/nietzsche.jpg",
        bio: "Filósofo alemão que criticou a moral tradicional e a religião, defendendo a criação de novos valores.",
        quote: "Aquele que tem um 'porquê' para viver pode suportar quase qualquer 'como'.",
        intro: "Obra de introdução ao autor: 'A Gaia Ciência'",
        introBuy: "https://www.planetadelivros.com.br/a-gaia-ciencia/208729",
        main: "Obra mais influencial: 'Além do Bem e do Mal'",
        mainBuy: "https://www.planetadelivros.com.br/alem-do-bem-e-do-mal/208731",
      },
      {
        name: "Arthur Schopenhauer",
        image: "/persons/schopenhauer.jpg",
        bio: "Filósofo alemão, conhecido por sua visão pessimista da vida e pela ideia do 'vontade de viver' como força fundamental.",
        quote: "A vida é um negócio que não cobre suas despesas.",
        intro: "Obra de introdução ao autor: 'O Mundo como Vontade e Representação' (seções introdutórias)",
        introBuy: "https://www.planetadelivros.com.br/o-mundo-como-vontade-e-representacao-secoes-introdutorias/208748",
        main: "Obra mais influencial: 'O Mundo como Vontade e Representação'",
        mainBuy: "https://www.planetadelivros.com.br/o-mundo-como-vontade-e-representacao/208749",
      },
      {
        name: "Emil Cioran",
        image: "/persons/cioran.jpg",
        bio: "Filósofo romeno, escreveu sobre o niilismo, a angústia existencial e a futilidade da vida.",
        quote: "A única maneira de lidar com a vida é se entregando ao absurdo.",
        intro: "Obra de introdução ao autor: 'Breviário de Decomposição'",
        introBuy: "https://www.planetadelivros.com.br/breviario-de-decomposicao/208750",
        main: "Obra mais influencial: 'O Livro dos Desassossegos'",
        mainBuy: "https://www.planetadelivros.com.br/o-livro-dos-desassossego/208751",
      },
    ],
  },
  Racionalismo: {
    thinkers: [
      {
        name: "René Descartes",
        image: "/persons/descartes.jpg",
        bio: "Filósofo francês, pai da filosofia moderna, conhecido pelo método da dúvida sistemática.",
        quote: "Penso, logo existo.",
        intro: "Obra de introdução: 'Discurso do Método'",
        introBuy: "https://www.example.com/discurso-do-metodo",
        main: "Obra mais influente: 'Meditações Metafísicas'",
        mainBuy: "https://www.example.com/meditacoes-metafisicas",
      },
      {
        name: "Spinoza",
        image: "/persons/spinoza.jpg",
        bio: "Filósofo holandês, desenvolveu uma visão monista do universo, identificando Deus com a natureza e enfatizando a razão.",
        quote: "A felicidade não é a recompensa da virtude, mas a própria virtude.",
        intro: "Introdução: 'Ética' (seções introdutórias)",
        introBuy: "https://www.planetadelivros.com.br/etica-secoes-introdutorias/208738",
        main: "Obra mais influencial: 'Ética'",
        mainBuy: "https://www.planetadelivros.com.br/etica/208739",
      },
      {
        name: "Leibniz",
        image: "/persons/leibniz.jpg",
        bio: "Filósofo e matemático alemão, conhecido por sua teoria das mônadas e pela defesa do otimismo metafísico.",
        quote: "Este é o melhor dos mundos possíveis.",
        intro: "Introdução: 'Discurso de Metafísica'",
        introBuy: "https://www.planetadelivros.com.br/discurso-de-metafisica/208746",
        main: "Obra mais influencial: 'Monadologia'",
        mainBuy: "https://www.planetadelivros.com.br/monadologia/208747",
      },
    ],
  },
  Positivismo: {
    thinkers: [
      {
        name: "John Stuart Mill",
        image: "/persons/mill.jpg",
        bio: "Filósofo e economista inglês, defensor do utilitarismo e dos direitos individuais.",
        quote: "A única liberdade que merece esse nome é a de buscar nosso próprio bem à nossa própria maneira.",
        intro: "Introdução: 'Sobre a Liberdade'",
        introBuy: "https://www.planetadelivros.com.br/sobre-a-liberdade/208742",
        main: "Obra mais influencial: 'Utilitarismo'",
        mainBuy: "https://www.planetadelivros.com.br/utilitarismo/208743",
      },
      {
        name: "Auguste Comte",
        image: "/persons/comte.jpg",
        bio: "Filósofo francês, fundador do positivismo, enfatizou a ciência empírica como base do conhecimento.",
        quote: "O amor por princípio e a ordem por base; o progresso por fim.",
        intro: "Introdução: 'Curso de Filosofia Positiva' (seções introdutórias)",
        introBuy: "https://www.planetadelivros.com.br/curso-de-filosofia-positiva-secoes-introdutorias/208740",
        main: "Obra mais influencial: 'Curso de Filosofia Positiva'",
        mainBuy: "https://www.planetadelivros.com.br/curso-de-filosofia-positiva/208741",
      },
    ],
  },
};

export default topThinkers;